services:
  api:
    build: ./backend
    container_name: safe-dr
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"

  frontend:
    build: ./front-end
    container_name: safe-drop-front
    ports:
      - "5171:5173"
    depends_on:
      - api
    volumes:
      - ./front-end:/app
      - /app/node_modules
